# Generated by Django 3.1.1 on 2020-10-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20201003_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='approved_by_manager',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='tables',
            name='delivered',
            field=models.BooleanField(default=0),
        ),
    ]
