# Generated by Django 3.1.1 on 2020-10-28 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20201026_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tables',
            old_name='title',
            new_name='equip',
        ),
    ]
